name: Github Actions 실행시켜보기

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "Hellow World"

      - name: 여러개 찍기
        run:
          echo "난 너를 몰라"
          echo "그걸 알아둬"
          echo "부서져도 몰라"
          echo "그걸 알아둬"
      - name: 깃헙 변수
        run:
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY